### ISSUE TITLE
make it possible to run benchmarks with custom configuration options passed to Coq's ./configure command

### ISSUE THREAD

**Issue by ejgallego** [coq/coq-bench#13]
[cc: @maximedenes ]

It seems that we are building Coq with `-native-compiler` on; however, doesn't that imply that a large part of the measured time is really spent in `ocamlc`?

Couldn't this interfere in when differentially testing some changes?

**Comment by ghost** [comment]
@ejgallego , what is `-native-compiler`? Why do you think we are using it?

(I am not sure whether this helps to make things more transparent, but we are using Ocaml switch `4.04.0`)

**Comment by ejgallego** [comment]
@matejkosik it is a configure option for Coq, I'm sure Maxime can tell you more.

**Comment by ghost** [comment]
What we do is to compile Coq configured in the same way as it is configured when one does `opam install coq`, i.e. no `-native-compiler` option.

If that is good idea or not, I let Maxime to decide.

**Comment by ejgallego** [comment]
Well, in a sense `-native-compiler` is just another configure option, so we could enable it per-benchmark. 

For better or worse we really need to support configure options if we intend `-flambda` to be ever used with Coq.

**Comment by ejgallego** [comment]
So if you wanna keep using OPAM, it looks to me that the easiest solution may be to make the opam script check configure variables to see if some special configure flags are needed.

**Comment by ghost** [comment]
How is Coq compiled is defined in the `opam` file. That one we (currently) generate (for the present needs, we could even use the [off-the-shelf version](https://github.com/coq/opam-coq-archive/blob/master/core-dev/packages/coq.dev/opam)). So we are free to put there what we want. At the moment, there is nothing special but we can change that (if need be).
