### ISSUE TITLE
Save benchmarks results

### ISSUE THREAD

**Issue by ejgallego** [coq/coq-bench#2]
We should benchmark every commit automatically and save the reports in a format that's easy to browse.

**Comment by ghost** [comment]
That makes sense to do also.

**Comment by ghost** [comment]
I've added your idea to the [TODO](https://github.com/matejkosik/coq-bench/blob/1ded88a13190718ef7ee3d98497d9e7996e3afff/two_points_on_the_same_branch.sh#L71) list.

**Comment by ejgallego** [comment]
I would rather have the issue closed when it is actually solved (hint, other people interested can search, collaborate and comment) but I guess it is your call.

**Comment by ghost** [comment]
Related to #11 .
