### ISSUE TITLE
coq-hott

### ISSUE THREAD

**Issue by ghost** [coq/coq-bench#21]
At the moment, we maintain a private `coq-hott` package.

The reason why we keep it private is that it is a too ugly.

It would make sense to cumb it a little bit and then share it publicly.

**Comment by psteckler** [comment]
@matejkosik could we setup Jenkins to install `coq-hott` from the private repo, so it can be benchmarked?

**Comment by ghost** [comment]
I have checked what is going on with HoTT on the Travis side and update the OPAM package.
Now `coq-hott` can be benchmarked (with Coq `master`). I have [restarted](https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/164/console) the job you have tried to run yesterday.

**Comment by ejgallego** [comment]
This is fixed TTBOMK.
