### ISSUE TITLE
refactor the benchmarking script

### ISSUE THREAD

**Issue by ghost** [coq/coq-bench#26]
[This](https://github.com/coq/coq-bench/blob/f06029879dc2202a3da1a9514bde5105c311d1c3/two_points_on_the_same_branch.sh#L400-L429) and [this](https://github.com/coq/coq-bench/blob/f06029879dc2202a3da1a9514bde5105c311d1c3/two_points_on_the_same_branch.sh#L433-L462) shuld be refactored.

**Comment by ejgallego** [comment]
Fixed by 79df91c56ffed7c22e58fe89578238e78c2b2325
