### ISSUE TITLE
missing periodic cleanup of generated files

### ISSUE THREAD

**Issue by ghost** [coq/coq-bench#29]
Each benchmarking job generates lot of files. We should define a periodic cleanup for the generated file (similarly to what we do we `pyrolyse`).

**Comment by ejgallego** [comment]
What's the status of this on the new setup @SkySkimmer ?

**Comment by SkySkimmer** [comment]
I think gitlab-runner handles this automatically
We should check though

**Comment by SkySkimmer** [comment]
AFAICT gitlab-runner keeps only the last build around, ie it cleans up on starting the next
