### ISSUE TITLE
Results should be saved incrementally

### ISSUE THREAD

**Issue by maximedenes** [coq/coq-bench#4]
The EConstr build failed after some hours, but I don't think the script saves the results as it gets them. It should, so that we don't waste time.

**Comment by maximedenes** [comment]
@matejkosik I think this issue is not real. I must have misunderstood what you told me. Results are in fact stored after each package is built, aren't they?

**Comment by ghost** [comment]
Results are stored. Although we do not do anything with them after the benchmarking job fails...

**Comment by maximedenes** [comment]
Yeah but then it's fine, if the script is also resilient to errors. Nothing specific to be done here, so I'm closing this issue.

**Comment by ghost** [comment]
Hm. I misinterpreted the objection. I have created a [commit](https://github.com/coq/coq-bench/commit/05e899fd5021aabbf1c452318f30c8e16bdcbfd8) where partial results are showed after we finish benchmarking each of the given OPAM packages. Right now I am testing this...

(even though the partial results will be downed in the log, anyway --- but it does not hurt to print them --- the only problem would be if we were benchmarking hundreds of packages; that would have slowed down the overall response of the benchmarking job because parsing as processing the data is quite some fun in that case).

**Comment by maximedenes** [comment]
@matejkosik Ok, that's even better. We won't need to dig in the files now.

**Comment by ghost** [comment]
So, what you will be seeing is something like this:

If you want to benchmark two packages `coq-sf` and `coq-flocq`, after `coq-sf` is proceed you get:
```
┌──────────────┬─────────────────────┬───────────────────────────────────┬───────────────────────────────────┐
│              │    user time [s]    │            CPU cycles             │         CPU instructions          │
│              │                     │                                   │                                   │
│ package_name │   NEW   OLD PDIFF   │          NEW          OLD PDIFF   │          NEW          OLD PDIFF   │
├──────────────┼─────────────────────┼───────────────────────────────────┼───────────────────────────────────┤
│       coq-sf │ 68.74 67.34 +2.08 % │ 255025910667 248524982549 +2.62 % │ 185150127613 184943537758 +0.11 % │
└──────────────┴─────────────────────┴───────────────────────────────────┴───────────────────────────────────┘
```
and after `coq-flocq` is processed:
```
┌──────────────┬──────────────────────┬────────────────────────────────────┬───────────────────────────────────┐
│              │    user time [s]     │             CPU cycles             │         CPU instructions          │
│              │                      │                                    │                                   │
│ package_name │   NEW   OLD  PDIFF   │          NEW          OLD  PDIFF   │          NEW          OLD PDIFF   │
├──────────────┼──────────────────────┼────────────────────────────────────┼───────────────────────────────────┤
│    coq-flocq │ 62.27 76.19 -18.27 % │ 231010041746 282244736786 -18.15 % │ 201885052577 201495194156 +0.19 % │
├──────────────┼──────────────────────┼────────────────────────────────────┼───────────────────────────────────┤
│       coq-sf │ 68.74 67.34  +2.08 % │ 255025910667 248524982549  +2.62 % │ 185150127613 184943537758 +0.11 % │
└──────────────┴──────────────────────┴────────────────────────────────────┴───────────────────────────────────┘
```

**Beware:** measurements are garbage in this case.

Etc.

**Comment by maximedenes** [comment]
Looks very good, thanks!
