### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by ejgallego** [coq/coq-bench#41]
Can we get a maintainer for this package?

I do volunteer to *co*-maintain.

**Comment by ejgallego** [comment]
Pinnnng.

**Comment by ejgallego** [comment]
Weekly ping.

**Comment by ejgallego** [comment]
Biweekly ping.

**Comment by ejgallego** [comment]
Uselesssss piiiiiiing.

**Comment by ejgallego** [comment]
So it seems that now people should get notified about this; what do we do with this repository?

I can help a bit, only thing I need to know is how to test changes.

**Comment by ejgallego** [comment]
Pinnnnng.

**Comment by SkySkimmer** [comment]
>So it seems that now people should get notified about this;

What people are these? I'm here from gitter.

**Comment by ejgallego** [comment]
As far as I know the repository has now 11 watchers, so that should be the people.

Anyways, let me cc people @maximedenes in particular, this is an urgent matter as the script is in need of much improvement so we ought to develop a maintainership procedure. Ideally we need:

- procedure to update the script on the machine.
- procedure to test the script, IMHO just building a couple of quick packages should do the work.
- list of maintaners.
- rollback procedure [in case of problems].

**Comment by ejgallego** [comment]
Pong.

**Comment by maximedenes** [comment]
Hi Emilio,

Unfortunately this repository is unmaintained AFAIK. I am fully booked for two weeks, I can try to have a look after that.

I can give you access to pendulum, though.

**Comment by ejgallego** [comment]
So indeed maybe I can co-maintain this [and rewrite it in OCaml]. @ppedrot , @SkySkimmer , @vbgl , as we us tend to be the most frequent users here, would you like to do a bench-maintainers team?

**Comment by vbgl** [comment]
Just discovering this repo… Could this be on the agenda of the next WG?

**Comment by ejgallego** [comment]
Sure, why not? My own roadmap is to rewrite the code in OCaml and integrate a bit better certain features / improve reporting, etc...

**Comment by SkySkimmer** [comment]
> So indeed maybe I can co-maintain this [and rewrite it in OCaml]. @ppedrot , @SkySkimmer , @vbgl , as we us tend to be the most frequent users here, would you like to do a bench-maintainers team?

I'm more on the user side. I guess I could look at PRs.

**Comment by ejgallego** [comment]
Also cc @gares of course.

**Comment by gares** [comment]
It is all yours.

**Comment by ejgallego** [comment]
Ok, so if I am not mistaken the conclusion is that I will become the maintainer of this repos; I'd love to have indeed a team; please state so.

Only pending bit is to document how the deployment is made on the server, @maximedenes has volunteered.

I will post more about my plans soon.

**Comment by ejgallego** [comment]
> Only pending bit is to document how the deployment is made on the server, @maximedenes has volunteered.

And once we have that I will close this issue.

**Comment by ejgallego** [comment]
The instructions should also provide a way to fix #44 for example.

@Zimmi48 , would you mind explaining more the status of Jenkins now? Is it the case that only the bench machine is running?

**Comment by maximedenes** [comment]
> @maximedenes has volunteered.

what?

**Comment by SkySkimmer** [comment]
That's what it says here: https://github.com/coq/coq/wiki/Next-Coq-Working-Group/_compare/ca62eb7d1a9e90b1d91c5cc11b41bdc76a579ef0...7264879265f3e08cc46ea8c6fdfb45c36bbf8c4b#diff-a17425d1e0c84adbbcf435ae6b42c9faR189

**Comment by ejgallego** [comment]
> > @maximedenes has volunteered.
> 
> what?

To document how to setup is done / give me access to the worker? You don't need to do anything fancy, give the pointers and I'll produce more principled doc.

**Comment by Zimmi48** [comment]
Indeed. I have killed mostly everything from Jenkins except the bench.

**Comment by ejgallego** [comment]
Thanks for the info @Zimmi48
