### ISSUE TITLE
General Roadmap of Coq Bench

### ISSUE THREAD

**Issue by ejgallego** [coq/coq-bench#49]
This is an attempt to share a general roadmap for Coq Bench so users can comment / collaborate.

The main idea is to rewrite the tool in OCaml and incorporate some code I had for bechmarking `oexp`. This would help having the tool run in users machines, and provide some more flexibility as to the kind of bench recipes we support.

**Versioning:** Coq bench does follow upstream Coq versioning, that is to say, 8.9 versions are expected to be used to benchmark Coq 8.9, 8.10 for Coq 8.10, etc...

For now we have two milestones:
- 8.9+shell: This milestone marks the end of development of the bash-based tool. Mainly we want to consolidate and document the tool, deployment, setup a brief CI, etc....
- 8.10+ocaml: This milestone marks the first release of a functioning OCaml-based bench tool. For this milestone we will basically have similar functionality to the bash-based tool.

**Comment by SkySkimmer** [comment]
>Versioning: Coq bench does follow upstream Coq versioning, that is to say, 8.9 versions are expected to be used to benchmark Coq 8.9, 8.10 for Coq 8.10, etc...

Why does the bench care about the coq version?

**Comment by ejgallego** [comment]
> Why does the bench care about the coq version?

It should not, but however there are always some configure changes, etc...

I prefer to follow this scheme.

**Comment by ejgallego** [comment]
But indeed you are right in the end it should not care.

**Comment by ejgallego** [comment]
Using OPAM 2 will introduce some incompatibilities, in particular with the way we specify OCaml versions.

As the bench is currently OPAM-based it will also mean that we may have some trouble testing older Coq versions in the CI.

**Comment by ejgallego** [comment]
In particular we will drop the `camlp5` dependency as to allow testing to trunk, which is IMO far more interesting; the script can be run standalone now so people interested on that kind of benchmarks should be able to do so.

**Comment by SkySkimmer** [comment]
outdated issue
