### ISSUE TITLE
Jenkins cleanup.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq-bench#51]
It seems we have quite a few Jenkins todo:
- update [a new version is available]
- remove stable / unneeded jobs
- remove pyrolise

cc: @maximedenes

**Comment by ejgallego** [comment]
cc also @herbelin @Zimmi48 as far as I understand coq-contribs / community is not running anything useful in jenkins, right?

**Comment by Zimmi48** [comment]
There used to be some coq-contribs tests running on Jenkins but there were failing all the time and no one was looking at them so I disabled them and no one complained. As for coq-community projects, they use their own Travis.

**Comment by ejgallego** [comment]
Not relevant anymore.
