### ISSUE TITLE
timing html broken

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq-bench#59]
https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/ws/625/html/ is a 404
https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/625/console prints related "/home/jenkins/git/coq-bench/two_points_on_the_same_branch.sh: line 333: cd: /home/jenkins/workspace/benchmark-part-of-the-branch/625/opam.NEW/4.07.1+flambda+no-flat-float-array/build/coq-mathcomp-character.dev//: No such file or directory"

**Comment by ejgallego** [comment]
Umm, where is OPAM 2 keeping the build output now?

**Comment by ejgallego** [comment]
Also opam 2.0 doesn't respect the `-j1` setting so it is very annoying :S What a buggy piece of ...

**Comment by ejgallego** [comment]
Ok, PR upcoming. bash is such a pain, so a better script here would be nice so it fails the CI.
