### ISSUE TITLE
Native compute support

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq-bench#74]
Currently native goes unbenched.

**Comment by ejgallego** [comment]
I will take care of this soon by fixing https://github.com/coq/coq/issues/8860

Note that I was afraid of native adding too much noise, for example if we bench two different OCaml versions timings for native stuff will indeed be not valid anymore.

**Comment by SkySkimmer** [comment]
What does valid mean in this context?

Gaëtan Gilbert

**Comment by ejgallego** [comment]
> What does valid mean in this context?

The timings are not only related to Coq but also to OCaml compilation performance and flags.

**Comment by SkySkimmer** [comment]
If we're benching different ocaml versions and flags presumably it's to 
see their impact no?

Gaëtan Gilbert

**Comment by ejgallego** [comment]
> If we're benching different ocaml versions and flags presumably it's to see their impact no?

Usually we want to see their impact on Coq itself, for example we don't care if compilation time for Coq is higher but the resulting binary is 10% faster; however for native users I dunno, sometimes we may care, sometimes we may not, so we need to be careful.

**Comment by ejgallego** [comment]
Indeed this needs to be configurable; in many cases enabling native is not wanted.

Also, allowing this to be configure per-switch would allow us to see the impact of native vs non-native.

**Comment by ejgallego** [comment]
Already submitted in Coq's main repos https://github.com/coq/coq/issues/13807
