### ISSUE TITLE
Updating Jenkins version

### ISSUE THREAD

**Issue by JasonGross** [coq/coq-bench#86]
In order to install Zulip integration (see https://coq.zulipchat.com/#narrow/stream/237655-Miscellaneous/topic/Bench.20notifications/near/197031723), we need to upgrade the version of Jenkins.  This can be done at https://ci.inria.fr/coq/manage and https://ci.inria.fr/coq/pluginManager/.  I am quite hesitant to do it myself, because if I end up borking the setup, I don't have login access to the machine to fix it.

**Comment by ejgallego** [comment]
Solved by porting to gitlab
