### ISSUE TITLE
bignums broken

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq-bench#87]
https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/ws/954/logs/coq-bignums.NEW.opam_install.1.stdout/*view*/
~~~
- File "./.coq-native/NBignums_BigNumPrelude.native", line 14, characters 2-60:
- Error: Unbound module NCoq_ZArith_Zdiv
- Error: Native compiler exited with status 2
- 
- Makefile.coq:719: recipe for target 'BigNumPrelude.vo' failed
~~~
Shouldn't it warn no-native-compiler?

**Comment by maximedenes** [comment]
@SkySkimmer the link above gives me a 404, is it expected?

**Comment by SkySkimmer** [comment]
The bench data gets deleted after a few days automatically.

**Comment by maximedenes** [comment]
Can you post a repro case?

**Comment by SkySkimmer** [comment]
in config/dune change native-compiler to yes
`dune build coq.install`
`dune exec -- coqc -native-compiler yes foo.v`
where foo.v is eg
~~~coq
Definition bla x y := x + y + x.
~~~
will produce 
~~~
File "/tmp/.coq-native/NTmp_foo.native", line 11, characters 2-39:
Error: Unbound module NCoq_Init_Nat
Error: Native compiler exited with status 2
~~~

**Comment by maximedenes** [comment]
Ah yes, sorry, this is indeed the (documented) requirement that in `coqc -native-compiler yes` requires the same flag on dependencies. We should probably store the value of this flag in `.vo` file and show a nice error message instead of this one. Would you mind opening a Coq issue for that?

**Comment by ejgallego** [comment]
Indeed I think this has changed, when this was not mandatory the old setup worked.
