### ISSUE TITLE
There should be only one Jenkins job for benchmarking

### ISSUE THREAD

**Issue by maximedenes** [coq/coq-bench#9]
And it should ask for:
1. A head repo
2. A head commit (can be a sha1, a branch name, etc.)
3. A base repo
4. A base commit (can be a sha1, a branch name, etc.)

3 should be the github repo by default.

I would advise against trying to guess 4.

**Comment by ghost** [comment]
Is there a way to clone Coq source code if I know only the SHA1?

(I remember myself wanting to do this but  I haven't figured out how to do that so I ended up asking the user for the branch name.)

**Comment by maximedenes** [comment]
```
git clone repo
git checkout sha1
```

**Comment by ghost** [comment]
Done.
