### ISSUE TITLE
Regular builds fail: coq_pr_number / comment_id must be set

### ISSUE THREAD

**Issue by ejgallego** [coq/coq-bench#90]
@JasonGross it seems your latest changes did break regular benchmark testing:

https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/965/console

I will revert #85 for now.

**Comment by JasonGross** [comment]
That link gives a 404.  Let me take a look, I think there's probably a better solution than revert

**Comment by JasonGross** [comment]
Can you try just commenting out the lines
```
check_variable "coq_pr_number"
check_variable "coq_pr_comment_id"
```
?

**Comment by ejgallego** [comment]
The builds have been already garbage-collected ? Or else somebody just removed them, I dunno, it is very bizarre that the log is gone.

The commit is reverted already, please make a PR to revert the revert and add a fix.

**Comment by ejgallego** [comment]
Not relevant anymore due to the migration.
