### ISSUE TITLE
Should the issues in this repository be transferred to the Coq repo and this repo archived?

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq-bench#92]

**Comment by ejgallego** [comment]
See also https://github.com/coq/coq/issues/13036 , indeed there was some work in progress here [including a better table printer] that became stale. I didn't have the cycles to look at this anymore, as all the work to move bench to Coq was not even discussed with the maintainers here.

**Comment by Zimmi48** [comment]
@coq/bench-maintainers Can you comment on this issue?

**Comment by SkySkimmer** [comment]
Transfer any you care about, leave the rest

**Comment by ejgallego** [comment]
Yes, we should archive this repos, working on it slowly tho, thanks for the reminder @Zimmi48

**Comment by SkySkimmer** [comment]
All the issues were either solved or not interesting so I closed them. I think we can archive.

**Comment by Zimmi48** [comment]
OK, I will archive. I think the README is clear enough that it needs no further update.
